= VM에 대한 검색을 예약합니다
:allow-uri-read: 




=== VM에 대한 검색을 예약합니다

BlueXP  재해 복구는 24시간마다 한 번씩 검색을 수행합니다. 이번 릴리스에서는 요구 사항에 맞게 검색 일정을 사용자 지정하고 필요할 때 성능에 미치는 영향을 줄일 수 있습니다. 예를 들어 VM 수가 많은 경우 검색 일정을 48시간마다 실행하도록 설정할 수 있습니다. VM 수가 적은 경우 12시간마다 실행되도록 검색 일정을 설정할 수 있습니다.

검색을 예약하기 위해 WAN을 사용하지 않는 경우 예약된 검색 옵션을 비활성화하고 언제든지 수동으로 검색을 새로 고칠 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트를 추가합니다"]참조하십시오.



=== 리소스 그룹 데이터 저장소가 지원됩니다

이전에는 VM별로 리소스 그룹을 생성할 수 있었습니다. 이번 릴리즈에서는 데이터 저장소별로 리소스 그룹을 생성할 수 있습니다. 복제 계획을 생성하고 해당 계획에 대한 리소스 그룹을 생성하는 경우 데이터 저장소의 모든 VM이 나열됩니다. 이 기능은 VM이 많은 경우 데이터 저장소를 기준으로 그룹화하려는 경우에 유용합니다.

다음과 같은 방법으로 데이터 저장소가 있는 리소스 그룹을 생성할 수 있습니다.

* 데이터 저장소를 사용하여 리소스 그룹을 추가할 때 데이터 저장소 목록을 볼 수 있습니다. 하나 이상의 데이터 저장소를 선택하여 리소스 그룹을 생성할 수 있습니다.
* 복제 계획을 만들고 계획 내에서 리소스 그룹을 만드는 경우 데이터 저장소의 VM을 볼 수 있습니다.


자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== 무료 평가판 또는 라이센스 만료 알림

이 릴리스는 무료 평가판이 라이센스를 취득할 수 있도록 60일 후에 만료된다는 알림을 제공합니다. 이 릴리스에서는 라이센스가 만료되는 날짜에 알림을 제공합니다.



=== 서비스 업데이트 알림

이 릴리스에서는 서비스가 업그레이드되고 서비스가 유지 관리 모드로 전환되었음을 나타내는 배너가 맨 위에 표시됩니다. 서비스가 업그레이드되면 배너가 나타나고 업그레이드가 완료되면 사라집니다. 업그레이드가 진행되는 동안 UI에서 계속 작업할 수 있지만 새 작업을 제출할 수는 없습니다. 업데이트가 완료되면 예약된 작업이 실행되고 서비스가 운영 모드로 돌아갑니다.
