= 서브넷 매핑
:allow-uri-read: 




=== 서브넷 매핑

이 릴리즈에서는 각 vCenter에 대해 서브넷을 추가할 수 있는 서브넷 매핑을 사용하여 새로운 방식으로 페일오버 시 IP 주소를 관리할 수 있습니다. 이 경우 IPv4 CIDR, 기본 게이트웨이 및 각 가상 네트워크에 대한 DNS를 정의합니다.

장애 조치 시 BlueXP  재해 복구는 매핑된 가상 네트워크에 제공된 CIDR을 확인하여 각 vNIC의 적절한 IP 주소를 결정하고 이를 사용하여 새 IP 주소를 파생시킵니다.

예를 들면 다음과 같습니다.

* NetworkA = 10.1.1.0/24
* NetworkB = 192.168.1.0/24


VM1에는 NetworkA에 연결된 vNIC(10.1.1.50)가 있습니다. NetworkA는 복제 계획 설정에서 NetworkB에 매핑됩니다.

장애 조치 시 BlueXP  재해 복구는 원래 IP 주소의 네트워크 부분(10.1.1)을 대체하고 원래 IP 주소(10.1.1.50)의 호스트 주소(.50)를 유지합니다. VM1의 경우 BlueXP  재해 복구는 NetworkB에 대한 CIDR 설정을 확인하고 NetworkB 네트워크 부분 192.168.1을 사용하는 동안 호스트 부분(.50)을 유지하여 VM1에 대한 새 IP 주소를 만듭니다. 새 IP는 192.168.1.50이 됩니다.

요약하면 호스트 주소는 동일하게 유지되지만 네트워크 주소는 사이트 서브넷 매핑에 구성된 것으로 대체됩니다. 따라서 페일오버 시 IP 주소 재할당을 보다 쉽게 관리할 수 있습니다. 특히 수백 개의 네트워크와 수천 개의 VM을 관리할 수 있는 경우 더욱 그렇습니다.

사이트에 서브넷 매핑을 포함하는 방법에 대한 자세한 내용은 을 참조하십시오link:../use/sites-add.html["vCenter 서버 사이트를 추가합니다"].



=== 보호를 건너뜁니다

이제 복제 계획 페일오버 후 서비스가 역방향 보호 관계를 자동으로 생성하지 않도록 보호를 건너뛸 수 있습니다. 이 기능은 복원된 사이트를 BlueXP  재해 복구 내에서 다시 온라인으로 전환하기 전에 해당 사이트에서 추가 작업을 수행하려는 경우에 유용합니다.

페일오버를 시작할 때 원래 소스 사이트가 온라인 상태인 경우 기본적으로 복제 계획의 각 볼륨에 대한 역방향 보호 관계가 자동으로 생성됩니다. 즉, 서비스가 타겟 사이트에서 소스 사이트로 다시 SnapMirror 관계를 생성합니다. 이 서비스는 페일백을 시작할 때 SnapMirror 관계도 자동으로 반전시킵니다.

이제 대체 작동을 시작할 때 * 보호 건너뛰기 * 옵션을 선택할 수 있습니다. 이 옵션을 사용하면 서비스에서 SnapMirror 관계를 자동으로 되돌리지 않습니다. 대신 쓰기 가능한 볼륨을 복제 계획의 양쪽에 남겨 둡니다.

원래 소스 사이트가 다시 온라인 상태가 되면 Replication Plan Actions 메뉴에서 * Protect resources * 를 선택하여 역방향 보호를 설정할 수 있습니다. 이렇게 하면 계획의 각 볼륨에 대한 역방향 복제 관계가 생성됩니다. 보호가 복원될 때까지 이 작업을 반복해서 실행할 수 있습니다. 보호가 복원되면 일반적인 방법으로 페일백을 시작할 수 있습니다.

보호를 건너뛰는 방법에 대한 자세한 내용은 을 link:../use/failover.html["애플리케이션을 원격 사이트로 페일오버합니다"]참조하십시오.



=== 복제 계획에서 SnapMirror 스케줄 업데이트

이제 BlueXP  재해 복구는 기본 ONTAP SnapMirror 정책 스케줄러나 ONTAP와의 타사 통합 같은 외부 스냅샷 관리 솔루션의 사용을 지원합니다. 복제 계획의 모든 데이터 저장소(볼륨)에 이미 다른 곳에서 관리되고 있는 SnapMirror 관계가 있는 경우 이러한 스냅샷을 BlueXP  재해 복구의 복구 지점으로 사용할 수 있습니다.

구성하려면 복제 계획 > 리소스 매핑 섹션에서 데이터 저장소 매핑을 구성할 때 * 플랫폼 관리 백업 및 보존 일정 사용 * 확인란을 선택합니다.

이 옵션을 선택하면 BlueXP  재해 복구가 백업 일정을 구성하지 않습니다. 그러나 테스트, 페일오버 및 페일백 작업을 위해 스냅샷을 계속 사용할 수 있으므로 보존 일정을 구성해야 합니다.

이 구성이 완료되면 서비스가 정기적으로 예약된 스냅샷을 만들지 않고 대신 외부 엔티티에 의존하여 해당 스냅샷을 생성하고 업데이트합니다.

복제 계획에서 외부 스냅샷 솔루션을 사용하는 link:../use/drplan-create.html["복제 계획을 생성합니다"]방법에 대한 자세한 내용은 을 참조하십시오.
