---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Amazon EVS와 Amazon FSx for NetApp ONTAP을 활용한 BlueXP 재해 복구 소개. 
---
= Amazon Elastic VMware Service 및 Amazon FSx for NetApp ONTAP을 사용한 BlueXP 재해 복구 소개
:allow-uri-read: 


[role="lead"]
VMware vSphere 기반과 같은 프로덕션 컴퓨팅 워크로드를 위해 가상화된 인프라에 대한 고객의 의존도가 점점 높아지고 있습니다. 이러한 가상 머신(VM)이 비즈니스에 더욱 중요해짐에 따라, 고객은 물리적 컴퓨팅 리소스와 동일한 유형의 재해로부터 VM을 보호해야 합니다. 현재 제공되는 재해 복구(DR) 솔루션은 복잡하고 비용이 많이 들며 리소스 사용량이 많습니다. 가상화된 인프라에 사용되는 최대 스토리지 공급업체인 NetApp은 모든 유형의 ONTAP 스토리지 호스팅 데이터를 보호하는 것과 동일한 방식으로 고객의 VM을 보호하는 데 큰 관심을 가지고 있습니다. 이러한 목표를 달성하기 위해 NetApp은 BlueXP 재해 복구 서비스를 개발했습니다.


NOTE: 아마존 EV에 관한 이 문서는 기술 미리보기로 제공됩니다. 이 사전 공개 오퍼링과 함께 NetApp은 일반 출시 이전에 서비스 세부 정보, 콘텐츠 및 일정을 수정할 권한을 보유합니다.

모든 재해 복구 솔루션의 주요 과제 중 하나는 재해 복구 복제 및 복구 인프라를 제공하기 위해 추가적인 컴퓨팅, 네트워크 및 스토리지 리소스를 구매, 구성 및 유지 관리하는 데 드는 추가 비용을 관리하는 것입니다. 중요한 온프레미스 가상 리소스를 보호하는 한 가지 일반적인 방법은 클라우드 호스팅 가상 리소스를 재해 복구 복제 및 복구 인프라로 사용하는 것입니다. Amazon은 NetApp ONTAP 호스팅 VM 인프라와 호환되는 비용 효율적인 리소스를 제공할 수 있는 이러한 솔루션의 한 예입니다.

Amazon은 가상 프라이빗 클라우드(VPC) 내에서 VMware Cloud Foundation을 지원하는 Amazon Elastic VMware Service(Amazon EVS)를 출시했습니다. Amazon EVS는 AWS의 복원력과 성능에 익숙한 VMware 소프트웨어 및 도구를 결합하여 Amazon EVS vCenter를 온프레미스 가상화 인프라의 확장 기능으로 통합할 수 있도록 지원합니다.

Amazon EVS는 스토리지 리소스를 기본으로 제공하지만, 스토리지 사용량이 많은 워크로드를 가진 조직에서는 네이티브 스토리지를 사용하면 효율성이 떨어질 수 있습니다. 이러한 경우 Amazon EVS를 Amazon FSx for NetApp ONTAP 스토리지(Amazon FSxN)와 함께 사용하면 더욱 유연한 스토리지 솔루션을 제공할 수 있습니다. 또한, 온프레미스에서 NetApp ONTAP 스토리지 솔루션을 사용하여 VMware 인프라를 호스팅하는 경우, Amazon EVS와 FSx for ONTAP을 함께 사용하면 온프레미스와 클라우드 호스팅 인프라 간에 동급 최고의 데이터 상호 운용성 및 보호 기능을 활용할 수 있습니다.

Amazon FSx for NetApp ONTAP에 대한 자세한 내용은 을 참조하십시오 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["NetApp ONTAP용 Amazon FSx 시작하기"^].
