---
sidebar: sidebar 
permalink: reference/vcenter-privileges.html 
keywords: disaster recovery, bluexp, vcenter, 
summary: 'vCenter 계정에는 BlueXP 재해 복구가 데이터 저장소 등록 및 등록 취소, VM 시작 및 중지, 가상 머신(VM) 재구성 등의 서비스를 수행할 수 있도록 최소 vCenter 권한 세트가 있어야 합니다. 다음 표에는 vCenter 클러스터와 인터페이스하기 위해 BlueXP 재해 복구에 필요한 모든 권한이 나와 있습니다.' 
---
= BlueXP 재해 복구에 필요한 vCenter 권한
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
vCenter 계정에는 BlueXP 재해 복구가 데이터 저장소 등록 및 등록 취소, VM 시작 및 중지, 가상 머신(VM) 재구성 등의 서비스를 수행할 수 있도록 최소 vCenter 권한 세트가 있어야 합니다. 다음 표에는 vCenter 클러스터와 인터페이스하기 위해 BlueXP 재해 복구에 필요한 모든 권한이 나와 있습니다.

[cols="25,35a,40a"]
|===
| 유형 | 권한 이름입니다 | 설명 


| * 데이터 저장소 *  a| 
데이터 저장소. 데이터 저장소를 구성합니다
 a| 
데이터 저장소를 구성하는 데 사용합니다.



|   a| 
데이터 저장소. 데이터 저장소를 제거합니다
 a| 
데이터 저장소를 제거하는 데 사용합니다.



| * 가상 시스템 *  a| 
가상 머신. 구성. 설정을 변경합니다
 a| 
일반 VM 설정을 변경하는 데 사용합니다.



|   a| 
가상 시스템. 구성. 장치 설정을 수정합니다
 a| 
기존 장치의 속성을 변경하는 데 사용합니다.



|   a| 
가상 머신.Configuration.Reload from path
 a| 
VM의 ID를 유지하면서 VM 구성 패치를 변경하는 데 사용합니다. VMware vCenter Site Recovery Manager와 같은 솔루션은 이 작업을 사용하여 페일오버 및 페일백 중에 VM 식별을 유지합니다.



|   a| 
가상 머신. 구성. 이름 바꾸기
 a| 
VM의 이름을 바꾸거나 VM의 연결된 노드를 수정하는 데 사용합니다.



|   a| 
가상 머신. 구성. 게스트 정보를 재설정합니다
 a| 
VM의 게스트 운영 체제 정보를 편집하는 데 사용합니다.



|   a| 
가상 머신. 구성. 메모리 변경
 a| 
VM에 할당된 메모리 양을 변경하는 데 사용합니다.



|   a| 
가상 머신. 구성. CPU 수를 변경합니다
 a| 
를 사용하여 가상 CPU 수를 변경합니다.



| * 가상 머신 게스트 *  a| 
가상 머신. 게스트 작업. 게스트 작업 수정
 a| 
VM으로 파일 전송 등 VM의 게스트 운영 체제 변경 사항이 포함된 VM 게스트 작업을 활성화합니다.



| * 가상 머신 상호 작용 *  a| 
가상 시스템. 상호 작용. 전원을 끕니다
 a| 
전원이 켜진 VM의 전원을 끄는 데 사용합니다. 이 작업은 게스트 운영 체제의 전원을 끕니다.



|   a| 
가상 시스템. 상호 작용. 전원을 켭니다
 a| 
전원이 꺼진 VM의 전원을 켜고 일시 중단된 VM을 재개하는 데 사용됩니다.



|   a| 
가상 머신. Interaction. VMware Tools 설치
 a| 
게스트 운영 체제용 CD-ROM으로 VMware Tools CD 설치 프로그램을 마운트하고 마운트 해제하는 데 사용합니다.



| * 가상 시스템 인벤토리 *  a| 
가상 머신. 인벤토리. 새로 만들기
 a| 
VM을 생성하고 실행할 리소스를 할당하는 데 사용합니다.



|   a| 
가상 머신. 인벤토리. 등록
 a| 
기존 VM을 vCenter Server 또는 호스트 인벤토리에 추가하는 데 사용합니다.



|   a| 
가상 머신. 인벤토리. 등록 취소
 a| 
vCenter Server 또는 호스트 인벤토리에서 VM 등록을 해제하는 데 사용합니다.



| * 가상 시스템 상태 *  a| 
가상 머신. Snapshot 관리: 스냅샷을 생성합니다
 a| 
VM의 현재 상태에서 스냅샷을 생성하는 데 사용합니다.



|   a| 
가상 머신. Snapshot 관리: 스냅샷을 제거합니다
 a| 
스냅샷 기록에서 스냅샷을 제거하는 데 사용합니다.



|   a| 
가상 머신. Snapshot 관리: 스냅샷으로 되돌립니다
 a| 
VM을 지정된 스냅샷의 상태로 설정하는 데 사용합니다.

|===