---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites, bluexp disaster recovery 
summary: BlueXP 재해 복구를 사용하기 전에 사용자 환경이 ONTAP 스토리지, VMware vCenter 클러스터 및 BlueXP 요구사항을 충족하는지 확인해야 합니다. 
---
= BlueXP 재해 복구의 사전 요구사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
BlueXP 재해 복구를 사용하기 전에 사용자 환경이 ONTAP 스토리지, VMware vCenter 클러스터 및 BlueXP 요구사항을 충족하는지 확인해야 합니다.



== ONTAP 스토리지 사전 요구 사항

이러한 사전 요구사항은 ONTAP 또는 Amazon FSx for NetApp ONTAP 인스턴스에 적용됩니다.

* 소스 및 대상 클러스터는 피어 관계가 있어야 합니다.
* 재해 복구 볼륨을 호스팅할 SVM이 대상 클러스터에 존재해야 합니다.
* 소스 SVM 및 타겟 SVM에는 피어 관계가 있어야 합니다.
+

NOTE: 대상 SVM 또는 SVM에서 재해 복구 볼륨을 미리 생성하면 안 됩니다. BlueXP 재해 복구는 복제 계획에 필요한 대상 볼륨을 생성합니다.

* Amazon FSx for NetApp ONTAP을 사용하여 구축하는 경우 다음 사전 요구사항이 적용됩니다.
+
** VMware DR 데이터 저장소를 호스팅할 Amazon FSx for NetApp ONTAP 인스턴스가 VPC에 있어야 합니다. 에서 Amazon FSx for ONTAP 문서를 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["시작하는 방법"^]참조하십시오.






== VMware vCenter 클러스터 사전 요구 사항

이러한 사전 요구 사항은 온프레미스 vCenter 클러스터와 VMware Cloud for AWS SDDC(소프트웨어 정의 데이터 센터) 모두에 적용됩니다.

* BlueXP 재해 복구를 관리하려는 모든 VMware 클러스터를 ONTAP 볼륨에서 호스팅해야 합니다.
* BlueXP 재해 복구로 관리할 모든 VMware 데이터 저장소는 다음 프로토콜 중 하나를 사용해야 합니다.
+
** NFS 를 참조하십시오
** iSCSI 또는 FC 프로토콜을 사용하는 VMFS


* VMware Cloud SDDC를 사용하는 경우 다음과 같은 사전 요구 사항이 적용됩니다.
+
** VMware Cloud Console에서 Administrator 및 NSX Cloud Administrator의 서비스 역할을 사용합니다. 조직 역할에도 조직 소유자를 사용합니다. 을 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["VMware Cloud Foundations와 AWS FSx for NetApp ONTAP 설명서 사용"^]참조하십시오.
** VMware Cloud SDDC를 Amazon FSx for NetApp ONTAP 인스턴스에 연결합니다. 을 https://vmc.techzone.vmware.com/fsx-guide#overview["AWS 기반 VMware Cloud를 Amazon FSx for NetApp ONTAP 구축 정보와 통합"^]참조하십시오.






== BlueXP 사전 요구사항



=== BlueXP를 시작하십시오

아직 수행하지 않았다면 https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html["BlueXP 에 등록하고 조직을 생성하십시오"^]



=== ONTAP 및 VMware에 대한 자격 증명을 수집합니다

* BlueXP  재해 복구 관리에 사용될 BlueXP  프로젝트 내의 작업 환경에 Amazon FSx for ONTAP 및 AWS 자격 증명을 추가해야 합니다.
* BlueXP 재해 복구를 수행하려면 vCenter 자격 증명이 필요합니다. BlueXP 재해 복구에 사이트를 추가할 때 vCenter 자격 증명을 입력합니다.
+
필요한 vCenter 권한 목록은 섹션을 link:../reference/vcenter-privileges.html["BlueXP 재해 복구에 필요한 vCenter 권한"]참조하십시오. 사이트를 추가하는 방법에 대한 지침은 을 link:../use/sites-add.html["사이트를 추가합니다"]참조하십시오.





=== BlueXP Connector를 생성합니다

BlueXP Connector를 BlueXP에서 설정해야 한다. BlueXP Connector를 사용할 경우 재해 복구 서비스에 대한 적절한 기능이 여기에 포함됩니다.

* BlueXP 재해 복구는 표준 모드 Connector 구축에서만 작동합니다. 을 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["표준 모드에서 BlueXP 시작하기"^]참조하십시오.
* 필요한 BlueXP Connector 유형:
+
** * 온프레미스 간 재해 복구 *: 재해 복구 사이트에 BlueXP 온프레미스 커넥터를 설치합니다. 을 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["온-프레미스에 커넥터를 설치하고 설정합니다"^]참조하십시오.
** * 온-프레미스에서 AWS *: AWS VPC에 AWS용 BlueXP Connector를 설치합니다. 을 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html["AWS의 커넥터 설치 옵션"^]참조하십시오.
+

TIP: 온프레미스에서 온프레미스까지 BlueXP 온프레미스 커넥터를 사용합니다. 온프레미스에서 AWS로 전환할 경우, 소스 온프레미스 vCenter 및 타겟 온프레미스 vCenter에 액세스할 수 있는 BlueXP AWS Connector를 사용합니다.

** 설치된 BlueXP Connector는 BlueXP 재해 복구에서 관리할 VMware 클러스터에 액세스할 수 있어야 합니다.


* BlueXP  재해 복구로 관리할 모든 ONTAP 어레이를 BlueXP  재해 복구 관리에 사용되는 BlueXP  프로젝트 내의 모든 작업 환경에 추가해야 합니다.
+
을 https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["사내 ONTAP 클러스터에 대해 알아보십시오"^]참조하십시오.





== 워크로드 사전 요구 사항

응용 프로그램 정합성 보장 프로세스가 성공적으로 수행되도록 하려면 다음 사전 요구 사항을 적용합니다.

* 보호할 VM에서 VMware 툴(또는 Open VM 툴)이 실행되고 있는지 확인합니다.
* Microsoft SQL Server 또는 Oracle Database 또는 둘 모두를 실행하는 Windows VM의 경우 데이터베이스에 VSS writer가 활성화되어 있어야 합니다.
* Linux 운영 체제에서 실행되는 Oracle 데이터베이스에는 Oracle 데이터베이스 SYSDBA 역할에 대해 운영 체제 사용자 인증이 설정되어 있어야 합니다.

