---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites 
summary: 고객의 환경, 네트워크 액세스, 로그인 및 웹 브라우저에 대한 지원을 확인하여 BlueXP 재해 복구를 시작하십시오. 
---
= BlueXP 재해 복구의 사전 요구사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
운영 환경, 로그인, 네트워크 액세스 및 웹 브라우저의 준비 상태를 확인하여 시작하십시오.

BlueXP 재해 복구를 사용하려면 환경이 다음 요구사항을 충족하는지 확인해야 합니다.

* NetApp 스토리지가 있는 온프레미스 VMware 작업 환경
* AWS의 경우:
+
** Amazon FSx for NetApp ONTAP 파일 시스템 에서 Amazon FSx for ONTAP 문서를 참조하십시오 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["시작하는 방법"^].
** AWS에 SDDC(소프트웨어 정의 데이터 센터)가 있는 VMware 계정(Virtual Machines Cloud라고도 함) VMware Cloud Console에서 Administrator 및 NSX Cloud Administrator의 서비스 역할을 사용합니다. 조직 역할에도 조직 소유자를 사용합니다. 을 참조하십시오 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Virtual Machines Cloud 설명서"^].
** SDDC를 Amazon FSx for NetApp ONTAP에 연결합니다. 을 참조하십시오 https://vmc.techzone.vmware.com/fsx-guide#overview["AWS 기반 VMware Cloud를 Amazon FSx for NetApp ONTAP과 통합합니다"^].


* BlueXP의 경우:
+
** Amazon FSx for ONTAP 및 AWS 자격 증명이 BlueXP 작업 환경에 추가되었습니다.
** BlueXP Connector를 BlueXP에서 설정해야 합니다. 온프레미스 및 클라우드 커넥터는 ESXis를 사용하여 온프레미스 및 VMware Cloud(VMC) vCenter에 모두 연결되어 있어야 합니다. 이를 통해 백업, 장애 조치, 장애 복구 및 마이그레이션 기능이 필요한 네트워킹 및 스크립트 기능과 함께 제대로 작동할 수 있습니다.
+
BlueXP Connector는 소스 및 타겟 vCenter 서버 모두에 대한 자격 증명이 필요합니다. 을 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["BlueXP 빠른 시작"^] 및 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html["BlueXP 네트워킹 정보"^].

** 응용 프로그램 정합성 보장 프로세스가 성공적으로 수행되도록 하려면 다음과 같은 사전 요구 사항이 충족되어야 합니다.
+
*** 보호할 VM에서 VMware 툴(또는 Open VM 툴)이 실행되고 있는지 확인합니다.
*** SQL 또는 Oracle 또는 둘 다를 실행하는 Windows VM의 경우 데이터베이스에 VSS writer가 활성화되어 있어야 하며 데이터베이스가 안정적인 상태여야 합니다.
*** Linux 운영 체제에서 실행되는 Oracle 데이터베이스에는 Oracle 데이터베이스 SYSDBA 역할에 대해 운영 체제 사용자 인증이 설정되어 있어야 합니다.





