---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: BlueXP 재해 복구를 사용하려면 몇 단계를 수행하여 설정하십시오. 
---
= BlueXP 재해 복구를 위한 인프라 설정
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
BlueXP 재해 복구를 사용하려면 몇 가지 단계를 수행하여 AWS(Amazon Web Services)와 BlueXP에서 모두 설정하십시오.


TIP: 검토 link:../get-started/dr-prerequisites.html["필수 구성 요소"] 환경을 준비합니다.



== BlueXP  재해 복구에 대비해 사내 간 보호를 제공합니다

온프레미스 보호를 위한 BlueXP  재해 복구를 설정하기 전에 다음 요구사항이 충족되는지 확인하십시오.

* ONTAP 스토리지
+
** ONTAP 자격 증명이 있는지 확인하십시오.
** 재해 복구 사이트 작성 또는 확인
** 대상 ONTAP SVM을 생성하거나 확인합니다.
** 소스 및 대상 ONTAP SVM이 피어링되도록 해야 합니다.


* vCenter 클러스터
+
** 보호하려는 VM이 NFS 데이터 저장소(ONTAP NFS 볼륨 사용) 또는 VMFS 데이터 저장소(NetApp iSCSI LUN 사용)에서 호스팅되는지 확인합니다.
** BlueXP  DR에 대한 검토가 link:../reference/vcenter-privileges.html["vCenter Privileges 를 참조하십시오"]필요합니다.
** 기본 vCenter 관리자 계정이 아닌 재해 복구 사용자 계정을 생성하고 vCenter Privileges를 계정에 할당합니다.






=== 지능형 프록시 지원

BlueXP  커넥터는 지능형 프록시를 지원합니다. 지능형 프록시는 온프레미스 환경을 BlueXP  서비스에 연결하는 가볍고 안전하며 효율적인 방법입니다. VPN 또는 직접 인터넷 액세스 없이도 사용자 환경과 BlueXP  서비스 간에 보안 연결을 제공합니다. 이렇게 최적화된 프록시 구현은 로컬 네트워크 내에서 API 트래픽을 오프로드합니다.

프록시가 구성된 경우 BlueXP  재해 복구는 VMware 또는 ONTAP와 직접 통신을 시도하고 직접 통신이 실패할 경우 구성된 프록시를 사용합니다.

BlueXP  재해 복구 프록시를 구현하려면 HTTPS 프로토콜을 사용하여 커넥터와 vCenter Server 및 ONTAP 어레이 간에 포트 443 통신이 필요합니다. 커넥터 내의 BlueXP  재해 복구 에이전트는 작업을 수행할 때 VMware vSphere, VC 또는 ONTAP와 직접 통신합니다.

BlueXP 에서 설정하는 일반 프록시에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["프록시 서버를 사용하도록 Connector를 구성합니다"^].



== AWS를 사용하여 사내-클라우드 보호를 위한 BlueXP  재해 복구를 준비하십시오

AWS를 사용하여 온프레미스-클라우드 보호를 위한 BlueXP  재해 복구를 설정하려면 다음을 설정해야 합니다.

* AWS FSx for NetApp ONTAP를 설정합니다
* AWS SDDC 기반 VMware Cloud 설정




=== AWS FSx for NetApp ONTAP를 설정합니다

* Amazon FSx for NetApp ONTAP 파일 시스템을 생성합니다.
+
** FSx for ONTAP를 프로비저닝하고 구성합니다. Amazon FSx for NetApp ONTAP는 완전 관리형 서비스입니다. NetApp ONTAP 파일 시스템을 기반으로 구축되어 탁월한 안정성, 확장성, 고성능 및 풍부한 기능을 갖춘 파일 스토리지를 제공합니다.
** 및 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["NetApp ONTAP용 Amazon FSx를 빠르게 시작합니다"] 에 나와 있는 단계에 따라 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["기술 보고서 4938: Amazon FSx ONTAP을 AWS 기반 VMware Cloud를 통해 NFS 데이터 저장소로 마운트합니다"^] FSx for ONTAP을 프로비저닝하고 구성합니다.


* Amazon FSx for ONTAP을 작업 환경에 추가하고 FSx for ONTAP에 대한 AWS 자격 증명을 추가합니다.
* AWS FSx for ONTAP 인스턴스에서 대상 ONTAP SVM을 생성하거나 검증합니다.
* 온프레미스 소스 ONTAP 클러스터와 BlueXP 의 FSx for ONTAP 인스턴스 간의 복제를 구성합니다.


자세한 단계는 를 https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["FSx for ONTAP 작업 환경을 설정하는 방법"^] 참조하십시오.



=== AWS SDDC 기반 VMware Cloud 설정

https://www.vmware.com/products/vmc-on-aws.html["AWS 기반 VMware 클라우드"^] AWS 에코시스템의 VMware 기반 워크로드에 클라우드 네이티브 경험을 제공합니다. 각 VMware SDDC(소프트웨어 정의 데이터 센터)는 Amazon VPC(Virtual Private Cloud)에서 실행되며 전체 VMware 스택(vCenter Server 포함), NSX-T 소프트웨어 정의 네트워킹, vSAN 소프트웨어 정의 스토리지 및 워크로드에 컴퓨팅 및 스토리지 리소스를 제공하는 하나 이상의 ESXi 호스트를 제공합니다.

AWS에서 VMware Cloud 환경을 구성하려면 의 단계를 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["AWS에서 가상화 환경을 구축하고 구성합니다"^] 따르십시오. 재해 복구 목적으로 파일럿 라이트 클러스터를 사용할 수도 있습니다.
