---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: BlueXP 재해 복구를 사용하려면 몇 단계를 수행하여 설정하십시오. 
---
= BlueXP 재해 복구를 위한 인프라 설정
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
BlueXP 재해 복구를 사용하려면 몇 가지 단계를 수행하여 AWS(Amazon Web Services)와 BlueXP에서 모두 설정하십시오.


TIP: 검토 link:../get-started/dr-prerequisites.html["필수 구성 요소"] 환경을 준비합니다.



== BlueXP 재해 복구에 대비하십시오

* 운영 환경을 확인합니다.
+
** 보호하려는 VM이 NFS 데이터 저장소(ONTAP NFS 볼륨 사용) 또는 VMFS 데이터 저장소(NetApp iSCSI LUN 사용)에서 호스팅되는지 확인합니다.
** 사내 ONTAP 어레이, vCenter 및 AWS 호스팅 VMware 클라우드 인스턴스에 대한 자격 증명 및 액세스 키를 보유하고 있는지 확인합니다.


* 재해 복구 사이트 작성 또는 확인
+
** Amazon FSx 파일 시스템이 준비되었는지 생성하거나 확인합니다.
** 소스 및 대상 VM이 피어링되었는지 확인합니다.






== VMware Cloud for AWS SDDC 설정

VMware Cloud for AWS SDDC(소프트웨어 정의 데이터 센터)를 설정합니다.

* Amazon FSx for ONTAP 파일 시스템을 생성합니다. FSx for ONTAP를 프로비저닝하고 구성합니다. NetApp ONTAP용 Amazon FSx는 널리 사용되는 NetApp ONTAP 파일 시스템에 구축된 매우 안정적이고 확장 가능하며 고성능의 풍부한 기능 파일 스토리지를 제공하는 완전 관리형 서비스입니다.
* 이 단계와 여기 단계에 따라 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["링크"^] https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["NetApp ONTAP용 Amazon FSx를 빠르게 시작합니다"] FSx for NetApp ONTAP를 프로비저닝하고 구성합니다.
* Amazon FSx for NetApp ONTAP을 작업 환경에 추가하고 FSx for ONTAP에 대한 AWS 자격 증명을 추가합니다.
* AWS에서는 다음 단계를 수행해야 합니다.
+
** AWS 기반 VMware Cloud를 구축하고 구성합니다.
** VMware 계정을 사용하여 SDDC를 프로비저닝합니다. SDDC가 FSx for ONTAP와 연결되어 있는지 확인합니다.






=== VMware 클라우드를 구축합니다

https://www.vmware.com/products/vmc-on-aws.html["AWS 기반 VMware 클라우드"^] AWS 에코시스템의 VMware 기반 워크로드에 클라우드 네이티브 경험을 제공합니다. 각 VMware SDDC(소프트웨어 정의 데이터 센터)는 Amazon VPC(Virtual Private Cloud)에서 실행되며 전체 VMware 스택(vCenter Server 포함), NSX-T 소프트웨어 정의 네트워킹, vSAN 소프트웨어 정의 스토리지 및 워크로드에 컴퓨팅 및 스토리지 리소스를 제공하는 하나 이상의 ESXi 호스트를 제공합니다.

AWS에서 VMC 환경을 구성하려면 다음 단계를 수행하십시오 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["링크"^]. 파일럿 라이트 클러스터는 재해 복구 목적으로도 사용할 수 있습니다.



== 라이센스를 설정합니다

BlueXP 재해 복구를 통해 90일 무료 평가판에 등록할 수 있습니다.

다음 중 하나를 구입할 수 있습니다.

* AWS Marketplace의 용량제(PAYGO) 구독
* NLF(NetApp 라이센스 파일)인 BYOL(Bring Your Own License)


을 link:../get-started/dr-licensing.html["BlueXP 재해 복구 라이센스 설정"]참조하십시오.
