---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter 
summary: BlueXP 재해 복구는 재해 복구 워크플로우를 자동화하는 클라우드 기반 재해 복구 서비스입니다. VMware용 BlueXP 재해 복구를 사용하면 NetApp 클라우드 스토리지를 사용하여 ONTAP 스토리지를 실행하는 온프레미스 VMware 워크로드를 퍼블릭 클라우드의 VMware 소프트웨어 정의 데이터 센터로 복제하여 재해 복구 사이트로 복제할 수 있습니다. 
---
= 새로운 기능
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXP 재해 복구의 새로운 기능에 대해 알아보십시오.



== 2024년 3월 5일

BlueXP 재해 복구의 일반 가용성 릴리즈로, 다음 업데이트가 포함됩니다.

* * 라이센스 업데이트 *: BlueXP 재해 복구를 사용하면 90일 무료 평가판 또는 BYOL(Bring Your Own License File)에 가입할 수 있습니다. BYOL은 NetApp 영업 담당자로부터 얻은 NetApp 라이센스 파일(NLF)입니다 라이센스 일련 번호를 사용하여 BlueXP 디지털 지갑에서 BYOL을 활성화할 수 있습니다. BlueXP 재해 복구 비용은 데이터 저장소의 프로비저닝된 용량을 기반으로 합니다.
+
BlueXP 재해 복구의 라이센스 설정에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["라이센스를 설정합니다"].

+
모든 * BlueXP 서비스의 라이센스 관리에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["모든 BlueXP 서비스의 라이센스 관리"^].



* * 일정 편집 * : 이번 릴리스에서는 규정 준수 및 장애 조치 테스트를 테스트하는 일정을 설정하여 필요할 때 올바르게 작동하도록 할 수 있습니다.
+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].





== 2024년 2월 1일

이 BlueXP 재해 복구 사전 공개 릴리즈에는 다음 업데이트가 포함되어 있습니다.

* * 네트워크 향상 * : 이 릴리스에서는 이제 VM CPU 및 RAM 값의 크기를 조정할 수 있습니다. 이제 VM에 대한 네트워크 DHCP 또는 정적 IP 주소를 선택할 수도 있습니다.
+
** DHCP: 이 옵션을 선택하면 VM에 대한 자격 증명을 제공합니다.
** 정적 IP: 소스 VM에서 동일하거나 다른 정보를 선택할 수 있습니다. 원본과 동일한 을 선택하면 자격 증명을 입력할 필요가 없습니다. 반면 원본과 다른 정보를 사용하도록 선택한 경우 자격 증명, IP 주소, 서브넷 마스크, DNS 및 게이트웨이 정보를 제공할 수 있습니다.
+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



* * 사용자 정의 스크립트 * 는 이제 사후 장애 조치 프로세스로 포함될 수 있습니다. 사용자 지정 스크립트를 사용하면 페일오버 프로세스 후에 BlueXP 재해 복구로 스크립트를 실행할 수 있습니다. 예를 들어, 페일오버가 완료된 후 사용자 지정 스크립트를 사용하여 모든 데이터베이스 트랜잭션을 재개할 수 있습니다.
+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["원격 사이트로 페일오버"].

* * SnapMirror 관계 *: 이제 복제 계획을 개발하는 동안 SnapMirror 관계를 생성할 수 있습니다. 이전에는 BlueXP 재해 복구 외부에 관계를 생성해야 했습니다.
+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].

* * 정합성 보장 그룹 *: 복제 계획을 생성할 때 다른 볼륨과 다른 SVM의 VM을 포함할 수 있습니다. BlueXP 재해 복구를 통해 모든 볼륨을 포함하여 일관성 그룹 스냅샷을 생성하고 모든 2차 위치를 업데이트합니다.
+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].

* * VM 전원 공급 지연 옵션 *: 복제 계획을 생성할 때 리소스 그룹에 VM을 추가할 수 있습니다. 리소스 그룹을 사용하면 각 VM에 지연 시간을 설정하여 지연된 시퀀스에서 전원을 켤 수 있습니다.
+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].

* * 애플리케이션 정합성 보장 스냅샷 복사본 *: 애플리케이션 정합성이 보장된 스냅샷 복사본을 생성하도록 지정할 수 있습니다. 이 서비스는 응용 프로그램을 중지한 다음 스냅샷을 생성하여 응용 프로그램의 일관된 상태를 확보합니다.
+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].





== 2024년 1월 11일

이 BlueXP 재해 복구 사전 공개 릴리즈에는 다음 업데이트가 포함되어 있습니다.

* 이 릴리즈를 사용하면 대시보드에서 다른 페이지의 정보에 더 빠르게 액세스할 수 있습니다.


https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].



== 2023년 10월 20일

이 BlueXP 재해 복구 기능의 사전 공개 릴리즈에는 다음 업데이트가 포함됩니다.

이제 BlueXP 재해 복구를 사용하면 퍼블릭 클라우드와 더불어 다른 온프레미스 NFS 기반 VMware 환경 재해로부터 온프레미스 NFS 기반 VMware 워크로드를 보호할 수 있습니다. BlueXP 재해 복구를 통해 재해 복구 계획의 완료를 조율합니다.


NOTE: 이 미리 보기 서비스를 통해 NetApp은 일반 출시 이전에 서비스 세부 정보, 콘텐츠 및 일정을 수정할 권한을 보유합니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].



== 2023년 9월 27일

이 BlueXP 재해 복구 사전 공개 릴리즈에는 다음 업데이트가 포함되어 있습니다.

* * 대시보드 업데이트 * : 이제 대시보드의 옵션을 클릭하여 정보를 빠르게 검토할 수 있습니다. 또한 이제 대시보드에 페일오버 및 마이그레이션 상태가 표시됩니다.
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["대시보드에서 재해 복구 계획의 상태를 확인합니다"].

* * 복제 계획 업데이트 *:
+
** * RPO *: 이제 Replication Plan의 Datastores 섹션에 RPO(복구 지점 목표) 및 보존 카운트를 입력할 수 있습니다. 설정된 시간보다 오래되지 않은 존재해야 하는 데이터의 양을 나타냅니다. 예를 들어, 5분으로 설정할 경우 비즈니스 크리티컬 요구사항에 영향을 주지 않는 재해 발생 시 시스템에서 최대 5분의 데이터가 손실될 수 있습니다.
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].

** * 네트워킹 개선 사항 *: 복제 계획의 가상 머신 섹션에서 소스 및 대상 위치 간의 네트워킹을 매핑할 때 BlueXP 재해 복구는 이제 DHCP 또는 고정 IP의 두 가지 옵션을 제공합니다. 이전에는 DHCP만 지원되었습니다. 정적 IP의 경우 서브넷, 게이트웨이 및 DNS 서버를 구성합니다. 또한 이제 가상 머신에 대한 자격 증명을 입력할 수 있습니다.
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].

** * 스케줄 편집 * : 이제 복제 계획 스케줄을 업데이트할 수 있습니다.
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["자원 관리"].

** * SnapMirror 자동화 *: 이 릴리즈에서 복제 계획을 생성하는 동안 다음 구성 중 하나에서 소스 볼륨과 타겟 볼륨 간의 SnapMirror 관계를 정의할 수 있습니다.
+
*** 1 대 1
*** 팬아웃 아키텍처에 1개 또는 다대다
*** 정합성 보장 그룹으로서 다대수 1입니다
*** 다대다
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].









== 2023년 8월 1일

BlueXP 재해 복구 사전 공개는 재해 복구 워크플로우를 자동화하는 클라우드 기반 재해 복구 서비스입니다. 처음에는 BlueXP 재해 복구 미리보기를 통해 Amazon FSx for ONTAP를 통해 NetApp 스토리지를 실행하는 온프레미스 NFS 기반 VMware 워크로드를 AWS의 VMware Cloud(VMC)로 보호할 수 있습니다.


NOTE: 이 미리 보기 서비스를 통해 NetApp은 일반 출시 이전에 서비스 세부 정보, 콘텐츠 및 일정을 수정할 권한을 보유합니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].

이 릴리스에는 다음 업데이트가 포함됩니다.

* * 부트 순서를 위한 리소스 그룹 업데이트 *: 재해 복구 또는 복제 계획을 작성할 때 가상 컴퓨터를 기능 리소스 그룹에 추가할 수 있습니다. 리소스 그룹을 사용하면 요구 사항을 충족하는 논리적 그룹에 종속 가상 머신 세트를 배치할 수 있습니다. 예를 들어, 복구 시 실행할 수 있는 부팅 순서가 그룹에 포함될 수 있습니다. 이 릴리즈에서는 각 리소스 그룹에 하나 이상의 가상 머신을 포함할 수 있습니다. 가상 머신은 계획에 가상 머신을 포함하는 순서에 따라 전원이 켜집니다. 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["리소스 그룹을 복제하고 할당할 애플리케이션을 선택합니다"].
* * 복제 검증 *: 재해 복구 또는 복제 계획을 생성한 후 마법사에서 재발을 식별하고 재해 복구 사이트로의 복제를 시작하면 BlueXP 재해 복구에서는 30분마다 계획이 실제로 이루어지고 있는지 확인합니다. 작업 모니터 페이지에서 진행 상황을 모니터링할 수 있습니다. 을 참조하십시오  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["애플리케이션을 다른 사이트에 복제"].
* * 복제 계획에는 복구 지점 목표(RPO) 전송 일정이 표시됩니다. *: 재해 복구 또는 복제 계획을 생성할 때 VM을 선택합니다. 이 릴리즈에서는 이제 데이터 저장소 또는 VM과 연결된 각 볼륨과 연결된 SnapMirror를 볼 수 있습니다. SnapMirror 일정과 연결된 RPO 전송 일정을 확인할 수도 있습니다. RPO는 백업 일정이 재해 발생 후 복구하기에 충분한지 여부를 확인하는 데 도움이 됩니다. 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].
* * 작업 모니터 업데이트 *: 작업 모니터 페이지에는 작업의 최신 상태를 확인할 수 있도록 새로 고침 옵션이 포함되어 있습니다. 을 참조하십시오  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["재해 복구 작업을 모니터링합니다"].




== 2023년 5월 18일

BlueXP 재해 복구의 최초 릴리즈입니다.

BlueXP 재해 복구는 재해 복구 워크플로우를 자동화하는 클라우드 기반 재해 복구 서비스입니다. 처음에는 BlueXP 재해 복구 미리보기를 통해 Amazon FSx for ONTAP를 통해 NetApp 스토리지를 실행하는 온프레미스 NFS 기반 VMware 워크로드를 AWS의 VMware Cloud(VMC)로 보호할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].
