---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: BlueXP 재해 복구는 재해 복구 워크플로우를 자동화하는 클라우드 기반 재해 복구 서비스입니다. VMware용 BlueXP 재해 복구를 사용하면 NetApp 클라우드 스토리지를 사용하여 ONTAP 스토리지를 실행하는 온프레미스 VMware 워크로드를 퍼블릭 클라우드의 VMware 소프트웨어 정의 데이터 센터로 복제하여 재해 복구 사이트로 복제할 수 있습니다. 
---
= BlueXP  재해 복구의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXP 재해 복구의 새로운 기능에 대해 알아보십시오.



== 2025년 9월 15일

버전 4.3.5P3



=== 테스트 장애 조치를 위한 스크립트 구성

이 릴리스를 사용하면 테스트 장애 조치 프로세스 중에 VM의 전원을 켠 후 스크립트를 실행할 수 있습니다.  이를 통해 스크립트를 테스트하고 검증할 수 있습니다.  예를 들어, NFS 마운트를 새로운 대상 서버를 가리키도록 업데이트하여 게스트 애플리케이션이 완전히 온라인 상태가 되고 복구 프로세스를 종단 간에 테스트할 수 있습니다.

장애 조치 프로세스에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["애플리케이션을 원격 사이트로 페일오버합니다"] .



=== 개선된 장애 복구 프로세스

장애 조치 중에는 검색이 완료될 때까지 장애 복구 프로세스가 비활성화됩니다.  이를 통해 장애 복구를 시작하기 전에 모든 구성이 올바르게 식별되고 설명되며 오류 위험이 줄어듭니다.

장애 복구 프로세스에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failback.html["원래 소스로 애플리케이션을 다시 장애 조치합니다."] .



== 2025년 8월 4일

버전 4.2.5P2



=== BlueXP disaster recovery 업데이트

이 릴리스에는 다음 업데이트가 포함됩니다.

* 여러 스토리지 가상 머신에서 제공되는 동일한 LUN을 처리하기 위해 VMFS 지원이 개선되었습니다.
* 이미 마운트 해제되거나 삭제된 데이터 저장소를 처리하기 위해 테스트 해체 정리를 개선했습니다.
* 제공된 네트워크 내에 입력된 게이트웨이가 포함되어 있는지 확인할 수 있도록 서브넷 매핑이 개선되었습니다.
* VM 이름에 ".com"이 포함되어 있는 경우 복제 계획이 실패할 수 있는 문제를 수정했습니다.
* 복제 계획 생성의 일부로 볼륨을 생성할 때 대상 볼륨이 소스 볼륨과 동일하지 않도록 하는 제한이 제거되었습니다.
* Azure Marketplace에서 NetApp Intelligent Services에 대한 PAYGO(종량제) 구독 지원을 추가하고 무료 평가판 대화 상자에 Azure Marketplace에 대한 링크를 추가했습니다.
+
자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["BlueXP disaster recovery 라이선스"] 그리고 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["BlueXP 재해 복구를 위한 라이센스 설정"] .





== 2025년 7월 14일

버전 4.2.5



=== BlueXP disaster recovery 의 사용자 역할

BlueXP disaster recovery 이제 각 사용자가 특정 기능과 작업에 대해 갖는 액세스를 관리하는 역할을 사용합니다.

이 서비스는 BlueXP disaster recovery 에 특정한 다음 역할을 사용합니다.

* *재해 복구 관리자*: BlueXP disaster recovery 에서 모든 작업을 수행합니다.
* *재해 복구 장애 조치 관리자*: BlueXP disaster recovery 에서 장애 조치 및 마이그레이션 작업을 수행합니다.
* *재해 복구 애플리케이션 관리자*: 복제 계획을 만들고 수정하고 테스트 장애 조치를 시작합니다.
* *재해 복구 뷰어*: BlueXP disaster recovery 에서 정보를 볼 수 있지만, 어떤 작업도 수행할 수 없습니다.


BlueXP disaster recovery 서비스를 클릭하고 처음으로 구성하는 경우 *SnapCenterAdmin* 권한이나 *조직 관리자* 역할이 있어야 합니다.

자세한 내용은 을 참조하십시오  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["BlueXP disaster recovery 의 사용자 역할 및 권한"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 BlueXP 액세스 역할에 대해 알아보세요"^]..



=== BlueXP disaster recovery 의 기타 업데이트

* 향상된 네트워크 검색
* 확장성 개선:
+
** 모든 세부 정보 대신 필요한 메타데이터만 필터링
** VM 리소스를 더 빠르게 검색하고 업데이트하기 위한 검색 개선
** 데이터 검색 및 데이터 업데이트를 위한 메모리 최적화 및 성능 최적화
** vCenter SDK 클라이언트 생성 및 풀 관리 개선


* 다음 예약 또는 수동 검색 시 오래된 데이터 관리:
+
** vCenter에서 VM이 삭제되면 이제 BlueXP disaster recovery 복제 계획에서 자동으로 해당 VM을 제거합니다.
** vCenter에서 데이터 저장소 또는 네트워크가 삭제되면 이제 BlueXP disaster recovery 복제 계획 및 리소스 그룹에서도 해당 데이터 저장소 또는 네트워크를 삭제합니다.
** vCenter에서 클러스터, 호스트 또는 데이터 센터가 삭제되면 이제 BlueXP disaster recovery 복제 계획 및 리소스 그룹에서도 이를 삭제합니다.


* 이제 브라우저의 시크릿 모드에서 Swagger 문서에 액세스할 수 있습니다. BlueXP disaster recovery 환경에서는 설정 > API 문서에서 액세스할 수 있으며, 브라우저의 시크릿 모드에서 다음 URL을 통해 직접 액세스할 수도 있습니다.  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger 문서"^] .
* 장애 복구 작업 후 일부 상황에서 iGroup이 작업 완료 후에도 남아 있는 경우가 있었습니다. 이 업데이트는 iGroup이 오래된 경우 제거합니다.
* 복제 계획에 NFS FQDN이 사용된 경우, BlueXP disaster recovery 이제 해당 FQDN을 IP 주소로 확인합니다. 이 업데이트는 재해 복구 사이트에서 FQDN을 확인할 수 없는 경우에 유용합니다.
* UI 정렬 개선
* 성공적인 검색 후 vCenter 크기 조정 세부 정보를 캡처하기 위한 로그 개선




== 2025년 6월 30일

버전 4.2.4P2



=== 발견 개선

이 업데이트는 검색 프로세스를 개선하여 검색에 필요한 시간을 줄여줍니다.



== 2025년 6월 23일

버전 4.2.4P1



=== 서브넷 매핑 개선

이번 업데이트에서는 새로운 검색 기능을 통해 서브넷 매핑 추가 및 편집 대화 상자가 개선되었습니다. 이제 검색어를 입력하여 특정 서브넷을 빠르게 찾을 수 있으므로 서브넷 매핑 관리가 더욱 간편해졌습니다.



== 2025년 6월 9일

버전 4.2.4



=== Windows 로컬 관리자 암호 솔루션(LAPS) 지원

Windows 로컬 관리자 암호 솔루션(Windows LAPS)은 Active Directory의 로컬 관리자 계정의 암호를 자동으로 관리하고 백업하는 Windows 기능입니다.

이제 도메인 컨트롤러 정보를 제공하여 서브넷 매핑 옵션을 선택하고 LAPS 옵션을 선택할 수 있습니다. 이 옵션을 사용하면 각 가상 머신에 비밀번호를 입력할 필요가 없습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



== 2025년 5월 13일

버전 4.2.3



=== 서브넷 매핑

이 릴리즈에서는 각 vCenter에 대해 서브넷을 추가할 수 있는 서브넷 매핑을 사용하여 새로운 방식으로 페일오버 시 IP 주소를 관리할 수 있습니다. 이 경우 IPv4 CIDR, 기본 게이트웨이 및 각 가상 네트워크에 대한 DNS를 정의합니다.

장애 조치 시 BlueXP  재해 복구는 매핑된 가상 네트워크에 제공된 CIDR을 확인하여 각 vNIC의 적절한 IP 주소를 결정하고 이를 사용하여 새 IP 주소를 파생시킵니다.

예를 들면 다음과 같습니다.

* NetworkA = 10.1.1.0/24
* NetworkB = 192.168.1.0/24


VM1에는 NetworkA에 연결된 vNIC(10.1.1.50)가 있습니다. NetworkA는 복제 계획 설정에서 NetworkB에 매핑됩니다.

장애 조치 시 BlueXP  재해 복구는 원래 IP 주소의 네트워크 부분(10.1.1)을 대체하고 원래 IP 주소(10.1.1.50)의 호스트 주소(.50)를 유지합니다. VM1의 경우 BlueXP  재해 복구는 NetworkB에 대한 CIDR 설정을 확인하고 NetworkB 네트워크 부분 192.168.1을 사용하는 동안 호스트 부분(.50)을 유지하여 VM1에 대한 새 IP 주소를 만듭니다. 새 IP는 192.168.1.50이 됩니다.

요약하면 호스트 주소는 동일하게 유지되지만 네트워크 주소는 사이트 서브넷 매핑에 구성된 것으로 대체됩니다. 따라서 페일오버 시 IP 주소 재할당을 보다 쉽게 관리할 수 있습니다. 특히 수백 개의 네트워크와 수천 개의 VM을 관리할 수 있는 경우 더욱 그렇습니다.

사이트에서 서브넷 매핑을 포함하는 방법에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트를 추가합니다"]참조하십시오.



=== 보호를 건너뜁니다

이제 복제 계획 페일오버 후 서비스가 역방향 보호 관계를 자동으로 생성하지 않도록 보호를 건너뛸 수 있습니다. 이 기능은 복원된 사이트를 BlueXP  재해 복구 내에서 다시 온라인으로 전환하기 전에 해당 사이트에서 추가 작업을 수행하려는 경우에 유용합니다.

페일오버를 시작할 때 원래 소스 사이트가 온라인 상태인 경우 기본적으로 복제 계획의 각 볼륨에 대한 역방향 보호 관계가 자동으로 생성됩니다. 즉, 서비스가 타겟 사이트에서 소스 사이트로 다시 SnapMirror 관계를 생성합니다. 이 서비스는 페일백을 시작할 때 SnapMirror 관계도 자동으로 반전시킵니다.

이제 대체 작동을 시작할 때 * 보호 건너뛰기 * 옵션을 선택할 수 있습니다. 이 옵션을 사용하면 서비스에서 SnapMirror 관계를 자동으로 되돌리지 않습니다. 대신 쓰기 가능한 볼륨을 복제 계획의 양쪽에 남겨 둡니다.

원래 소스 사이트가 다시 온라인 상태가 되면 Replication Plan Actions 메뉴에서 * Protect resources * 를 선택하여 역방향 보호를 설정할 수 있습니다. 이렇게 하면 계획의 각 볼륨에 대한 역방향 복제 관계가 생성됩니다. 보호가 복원될 때까지 이 작업을 반복해서 실행할 수 있습니다. 보호가 복원되면 일반적인 방법으로 페일백을 시작할 수 있습니다.

건너뛰는 보호에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["애플리케이션을 원격 사이트로 페일오버합니다"]참조하십시오.



=== 복제 계획에서 SnapMirror 스케줄 업데이트

이제 BlueXP  재해 복구는 기본 ONTAP SnapMirror 정책 스케줄러나 ONTAP와의 타사 통합 같은 외부 스냅샷 관리 솔루션의 사용을 지원합니다. 복제 계획의 모든 데이터 저장소(볼륨)에 이미 다른 곳에서 관리되고 있는 SnapMirror 관계가 있는 경우 이러한 스냅샷을 BlueXP  재해 복구의 복구 지점으로 사용할 수 있습니다.

구성하려면 복제 계획 > 리소스 매핑 섹션에서 데이터 저장소 매핑을 구성할 때 * 플랫폼 관리 백업 및 보존 일정 사용 * 확인란을 선택합니다.

이 옵션을 선택하면 BlueXP  재해 복구에서 백업 일정을 구성하지 않습니다. 그러나 테스트, 페일오버 및 페일백 작업을 위해 스냅샷을 계속 사용할 수 있으므로 보존 일정을 구성해야 합니다.

이 구성이 완료되면 서비스가 정기적으로 예약된 스냅샷을 만들지 않고 대신 외부 엔티티에 의존하여 해당 스냅샷을 생성하고 업데이트합니다.

복제 계획에서 외부 스냅샷 솔루션을 사용하는 방법에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



== 2025년 4월 16일

버전 4.2.2



=== VM에 대한 검색을 예약합니다

BlueXP  재해 복구는 24시간마다 한 번씩 검색을 수행합니다. 이번 릴리스에서는 요구 사항에 맞게 검색 일정을 사용자 지정하고 필요할 때 성능에 미치는 영향을 줄일 수 있습니다. 예를 들어 VM 수가 많은 경우 검색 일정을 48시간마다 실행하도록 설정할 수 있습니다. VM 수가 적은 경우 12시간마다 실행되도록 검색 일정을 설정할 수 있습니다.

검색을 예약하기 위해 WAN을 사용하지 않는 경우 예약된 검색 옵션을 비활성화하고 언제든지 수동으로 검색을 새로 고칠 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트를 추가합니다"]참조하십시오.



=== 리소스 그룹 데이터 저장소가 지원됩니다

이전에는 VM별로 리소스 그룹을 생성할 수 있었습니다. 이번 릴리즈에서는 데이터 저장소별로 리소스 그룹을 생성할 수 있습니다. 복제 계획을 생성하고 해당 계획에 대한 리소스 그룹을 생성하는 경우 데이터 저장소의 모든 VM이 나열됩니다. 이 기능은 VM이 많은 경우 데이터 저장소를 기준으로 그룹화하려는 경우에 유용합니다.

다음과 같은 방법으로 데이터 저장소가 있는 리소스 그룹을 생성할 수 있습니다.

* 데이터 저장소를 사용하여 리소스 그룹을 추가할 때 데이터 저장소 목록을 볼 수 있습니다. 하나 이상의 데이터 저장소를 선택하여 리소스 그룹을 생성할 수 있습니다.
* 복제 계획을 만들고 계획 내에서 리소스 그룹을 만드는 경우 데이터 저장소의 VM을 볼 수 있습니다.


자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== 무료 평가판 또는 라이센스 만료 알림

이 릴리스는 무료 평가판이 라이센스를 취득할 수 있도록 60일 후에 만료된다는 알림을 제공합니다. 이 릴리스에서는 라이센스가 만료되는 날짜에 알림을 제공합니다.



=== 서비스 업데이트 알림

이 릴리스에서는 서비스가 업그레이드되고 서비스가 유지 관리 모드로 전환되었음을 나타내는 배너가 맨 위에 표시됩니다. 서비스가 업그레이드되면 배너가 나타나고 업그레이드가 완료되면 사라집니다. 업그레이드가 진행되는 동안 UI에서 계속 작업할 수 있지만 새 작업을 제출할 수는 없습니다. 업데이트가 완료되면 예약된 작업이 실행되고 서비스가 운영 모드로 돌아갑니다.



== 2025년 3월 10일

버전 4.2.1



=== 지능형 프록시 지원

BlueXP  커넥터는 지능형 프록시를 지원합니다. 지능형 프록시는 온프레미스 환경을 BlueXP  서비스에 연결하는 가볍고 안전하며 효율적인 방법입니다. VPN 또는 직접 인터넷 액세스 없이도 사용자 환경과 BlueXP  서비스 간에 보안 연결을 제공합니다. 이렇게 최적화된 프록시 구현은 로컬 네트워크 내에서 API 트래픽을 오프로드합니다.

프록시가 구성된 경우 BlueXP  재해 복구는 VMware 또는 ONTAP와 직접 통신을 시도하고 직접 통신이 실패할 경우 구성된 프록시를 사용합니다.

BlueXP  재해 복구 프록시를 구현하려면 HTTPS 프로토콜을 사용하여 커넥터와 vCenter Server 및 ONTAP 어레이 간에 포트 443 통신이 필요합니다. 커넥터 내의 BlueXP  재해 복구 에이전트는 작업을 수행할 때 VMware vSphere, VC 또는 ONTAP와 직접 통신합니다.

BlueXP  재해 복구용 지능형 프록시에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["BlueXP 재해 복구를 위한 인프라 설정"].

BlueXP 에서 설정하는 일반 프록시에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["프록시 서버를 사용하도록 Connector를 구성합니다"^].



=== 무료 평가판을 언제든지 종료합니다

당신은 어떤 갈래 또는 당신은 그것이 만료될 때까지 기다릴 수 무료 평가판을 중지할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["무료 평가판을 종료합니다"]참조하십시오.



== 2025년 2월 19일

버전 4.2



=== ASA R2는 VMFS 스토리지의 VM 및 데이터 저장소를 지원합니다

이번 BlueXP  재해 복구 릴리즈는 VMFS 스토리지의 VM 및 데이터 저장소용 ASA R2를 지원합니다. ASA R2 시스템에서 ONTAP 소프트웨어는 필수 SAN 기능을 지원하는 동시에 SAN 환경에서 지원되지 않는 기능을 제거합니다.

이 릴리즈에서는 ASA R2에 대해 다음 기능을 지원합니다.

* 운영 스토리지에 대한 정합성 보장 그룹 프로비저닝(플랫 정합성 보장 그룹만 해당, 즉 계층 구조가 없는 한 레벨만 해당)
* SnapMirror 자동화를 포함한 백업(일관성 그룹) 작업


BlueXP  재해 복구에서 ASA R2에 대한 지원은 ONTAP 9.16.1을 사용합니다.

데이터 저장소는 ONTAP 볼륨 또는 ASA R2 스토리지 유닛에 마운트할 수 있지만 BlueXP  재해 복구의 리소스 그룹에 ONTAP의 데이터 저장소와 ASA R2의 데이터 저장소를 모두 포함할 수는 없습니다. ONTAP에서 데이터 저장소를 선택하거나 리소스 그룹의 ASA R2에서 데이터 저장소를 선택할 수 있습니다.



== 2024년 10월 30일



=== 보고

이제 보고서를 생성하고 다운로드하여 환경 분석에 도움을 줄 수 있습니다. 사전 설계된 보고서는 페일오버와 장애 복구를 요약하고, 모든 사이트에 대한 복제 세부 정보를 표시하며, 지난 7일 동안의 작업 세부 정보를 표시합니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["재해 복구 보고서를 생성합니다"]참조하십시오.



=== 30일 무료 평가판

이제 BlueXP  재해 복구의 30일 무료 평가판에 등록할 수 있습니다. 이전에는 무료 평가판이 90일이었습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["라이센스를 설정합니다"]참조하십시오.



=== 복제 계획 해제 및 설정

이전 릴리스에는 매일 및 매주 일정을 지원하는 데 필요한 페일오버 테스트 일정 구조의 업데이트가 포함되었습니다. 이 업데이트를 수행하려면 새로운 일별 및 주별 페일오버 테스트 일정을 사용할 수 있도록 모든 기존 복제 계획을 비활성화했다가 다시 활성화해야 합니다. 이는 일회성 요구 사항입니다.

방법은 다음과 같습니다.

. 상단 메뉴에서 * Replication Plans * 를 선택합니다.
. 계획을 선택하고 조치 아이콘을 선택하여 드롭다운 메뉴를 표시합니다.
. 비활성화 * 를 선택합니다.
. 몇 분 후 * 활성화 * 를 선택합니다.




=== 폴더 매핑

복제 계획을 생성하고 컴퓨팅 리소스를 매핑할 때 데이터 센터, 클러스터 및 호스트에 대해 지정한 폴더에서 VM이 복구되도록 폴더를 매핑할 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== 장애 조치, 장애 복구 및 테스트 장애 조치에 대한 VM 세부 정보를 사용할 수 있습니다

장애가 발생하여 페일오버를 시작하거나, 페일백을 수행하거나, 장애 조치를 테스트하는 경우 이제 VM의 세부 정보를 보고 다시 시작하지 않은 VM을 식별할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["애플리케이션을 원격 사이트로 페일오버합니다"]참조하십시오.



=== VM 부팅 지연(부팅 순서 순서 순서 순서 지정)

이제 복제 계획을 생성할 때 계획의 각 VM에 대해 부팅 지연을 설정할 수 있습니다. 이렇게 하면 VM이 시작되도록 순서를 설정하여 이후의 우선 순위 VM이 시작되기 전에 우선 순위 VM이 모두 실행되도록 할 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== VM 운영 체제 정보

복제 계획을 생성하면 이제 계획의 각 VM에 대한 운영 체제를 볼 수 있습니다. 이 기능은 리소스 그룹에서 VM을 그룹화하는 방법을 결정하는 데 유용합니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== VM 이름 별칭

복제 계획을 생성할 때 이제 재해 복구 SIT의 VM 이름에 접두사 및 접미사를 추가할 수 있습니다. 이렇게 하면 계획에 있는 VM에 대해 보다 자세한 이름을 사용할 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== 이전 스냅샷을 정리합니다

지정된 보존 횟수 이상으로 더 이상 필요하지 않은 모든 스냅샷을 삭제할 수 있습니다. 스냅샷 보존 수를 낮추면 스냅샷이 시간 경과에 따라 누적될 수 있으며, 이제 스냅샷을 제거하여 공간을 확보할 수 있습니다. 요청 시 또는 복제 계획을 삭제할 때 언제든지 이 작업을 수행할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["사이트, 리소스 그룹, 복제 계획, 데이터 저장소 및 가상 머신 정보를 관리합니다"]참조하십시오.



=== 스냅샷을 조정합니다

이제 소스와 타겟 간에 동기화되지 않은 스냅샷을 조정할 수 있습니다. 이 문제는 BlueXP  재해 복구 외부에 있는 타겟에서 스냅샷이 삭제된 경우에 발생할 수 있습니다. 이 서비스는 24시간마다 소스의 스냅샷을 자동으로 삭제합니다. 그러나 필요에 따라 이 작업을 수행할 수 있습니다. 이 기능을 사용하면 모든 사이트에서 스냅샷이 일관되게 유지되도록 할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["복제 계획을 관리합니다"]참조하십시오.



== 2024년 9월 20일



=== 사내에서 온프레미스까지 VMware VMFS 데이터 저장소를 지원합니다

이 릴리즈에는 사내 스토리지로 보호되는 iSCSI 및 FC용 VMware vSphere VMFS(Virtual Machine File System) 데이터 저장소에 마운트된 VM에 대한 지원이 포함되어 있습니다. 이전에는 iSCSI 및 FC용 VMFS 데이터 저장소를 지원하는 _technology preview_를 제공했습니다.

다음은 iSCSI 및 FC 프로토콜 모두에 대한 몇 가지 추가 고려 사항입니다.

* FC는 클라이언트 프런트 엔드 프로토콜에 대한 지원이며 복제용이 아닙니다.
* BlueXP  재해 복구는 ONTAP 볼륨당 하나의 LUN만 지원합니다. 볼륨에 여러 개의 LUN이 있어서는 안 됩니다.
* 모든 복제 계획의 경우 대상 ONTAP 볼륨은 보호된 VM을 호스팅하는 소스 ONTAP 볼륨과 동일한 프로토콜을 사용해야 합니다. 예를 들어, 소스에서 FC 프로토콜을 사용하는 경우 타겟도 FC를 사용해야 합니다.




== 2024년 8월 2일



=== 온프레미스부터 온프레미스 VMware VMFS 데이터 저장소용 FC 지원

이 릴리즈에는 온프레미스 스토리지로 보호되는 FC용 VMware vSphere VMFS(Virtual Machine File System) 데이터 저장소에 마운트된 VM에 대한 기술 미리 보기 _ 가 포함되어 있습니다. 이전에는 iSCSI용 VMFS 데이터 저장소를 지원하는 기술 미리 보기를 제공했습니다.


NOTE: NetApp는 사전 검토된 워크로드 용량에 대해 비용을 청구하지 않습니다.



=== 작업 취소

이 릴리스에서는 작업 모니터 UI에서 작업을 취소할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["작업을 모니터링합니다"]참조하십시오.



== 2024년 7월 17일



=== 페일오버 테스트 일정

이 릴리즈에는 일별 및 주별 일정을 지원하는 데 필요한 페일오버 테스트 일정 구조의 업데이트가 포함되어 있습니다. 이 업데이트를 수행하려면 새로운 일별 및 주별 페일오버 테스트 일정을 사용할 수 있도록 모든 기존 복제 계획을 비활성화했다가 다시 활성화해야 합니다. 이는 일회성 요구 사항입니다.

방법은 다음과 같습니다.

. 상단 메뉴에서 * Replication Plans * 를 선택합니다.
. 계획을 선택하고 조치 아이콘을 선택하여 드롭다운 메뉴를 표시합니다.
. 비활성화 * 를 선택합니다.
. 몇 분 후 * 활성화 * 를 선택합니다.




=== 복제 계획 업데이트

이 릴리즈에는 "스냅샷을 찾을 수 없음" 문제를 해결하는 복제 계획 데이터에 대한 업데이트가 포함되어 있습니다. 이렇게 하려면 모든 복제 계획의 보존 수를 1로 변경하고 필요 시 스냅샷을 시작해야 합니다. 이 프로세스는 새 백업을 생성하고 이전 백업을 모두 제거합니다.

방법은 다음과 같습니다.

. 상단 메뉴에서 * Replication Plans * 를 선택합니다.
. 복제 계획을 선택하고 * Failover mapping * 탭을 클릭한 다음 * Edit * 연필 아이콘을 클릭합니다.
. Datastores * 화살표를 클릭하여 확장합니다.
. 복제 계획에서 보존 횟수의 값을 확인합니다. 이 단계를 완료하면 이 원래 값을 복원해야 합니다.
. 카운트를 1로 줄입니다.
. 주문형 스냅샷을 시작합니다. 이렇게 하려면 복제 계획 페이지에서 계획을 선택하고 작업 아이콘을 클릭한 다음 * 지금 스냅샷 생성 * 을 선택합니다.
. 스냅샷 작업이 성공적으로 완료되면 첫 번째 단계에서 기록한 원래 값으로 복제 계획의 개수를 증가시킵니다.
. 모든 기존 복제 계획에 대해 이 단계를 반복합니다.




== 2024년 7월 5일

이 BlueXP 재해 복구 릴리즈에는 다음 업데이트가 포함됩니다.



=== AFF A-Series 지원

이 릴리즈는 NetApp AFF A-Series 하드웨어 플랫폼을 지원합니다.



=== 사내에서 온프레미스까지 VMware VMFS 데이터 저장소를 지원합니다

이 릴리즈에는 온프레미스 스토리지로 보호되는 VMware vSphere VMFS(Virtual Machine File System) 데이터 저장소에 마운트된 VM에 대한 _technology preview_가 포함되어 있습니다. 이번 릴리즈에서는 VMFS 데이터 저장소가 있는 사내 VMware 환경에서 온-프레미스 VMware 워크로드를 대상으로 하는 기술 미리보기에서 재해 복구가 지원됩니다.


NOTE: NetApp는 사전 검토된 워크로드 용량에 대해 비용을 청구하지 않습니다.



=== 복제 계획 업데이트

애플리케이션 페이지에서 데이터 저장소별로 VM을 필터링하고 리소스 매핑 페이지에서 더 많은 타겟 세부 정보를 선택하여 복제 계획을 보다 쉽게 추가할 수 있습니다. 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



=== 복제 계획을 편집합니다

이번 릴리스에서는 장애 조치 매핑 페이지가 보다 명확하게 개선되었습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["계획을 관리합니다"]참조하십시오.



=== VM 편집

이번 릴리스에서는 계획에서 VM을 편집하는 프로세스에 몇 가지 사소한 UI 개선 사항이 포함되었습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["VM 관리"]참조하십시오.



=== 업데이트 페일오버

이제 페일오버를 시작하기 전에 VM의 상태와 VM의 전원이 켜져 있는지 여부를 확인할 수 있습니다. 이제 페일오버 프로세스를 통해 스냅샷을 지금 생성하거나 스냅샷을 선택할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["애플리케이션을 원격 사이트로 페일오버합니다"]참조하십시오.



=== 페일오버 테스트 일정

이제 페일오버 테스트를 편집하고 페일오버 테스트에 대한 일별, 주별 및 월별 스케줄을 설정할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["계획을 관리합니다"]참조하십시오.



=== 필수 구성 요소 정보 업데이트

BlueXP  재해 복구 사전 요구 사항 정보가 업데이트되었습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["BlueXP 재해 복구의 사전 요구사항"]참조하십시오.



== 2024년 5월 15일

이 BlueXP 재해 복구 릴리즈에는 다음 업데이트가 포함됩니다.



=== 온프레미스에서 온프레미스로 VMware 워크로드 복제

이 기능은 일반 가용성 기능으로 릴리스되었습니다. 이전에는 기능이 제한된 기술 미리 보기였습니다.



=== 라이선스 업데이트

BlueXP  재해 복구를 사용하면 90일 무료 평가판에 등록하거나, Amazon Marketplace에서 PAYGO(Pay-as-you-Go) 구독 요금을 구매하거나, NetApp 세일즈 담당자 또는 NetApp 지원 사이트(NSS)로부터 받은 NLF(NetApp 라이센스 파일)인 BYOL(Bring Your Own License) 라이센스를 구매할 수 있습니다.

BlueXP 재해 복구의 라이센스 설정에 대한 자세한 내용은 을 참조하십시오 link:../get-started/dr-licensing.html["라이센스를 설정합니다"].

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].



== 2024년 3월 5일

BlueXP 재해 복구의 일반 가용성 릴리즈로, 다음 업데이트가 포함됩니다.



=== 라이선스 업데이트

BlueXP  재해 복구를 사용하면 90일 무료 평가판 또는 BYOL(Bring Your Own License NetApp File)에 가입할 수 있습니다. BYOL(Bring Your Own License File)은 NetApp 영업 담당자가 제공합니다 라이센스 일련 번호를 사용하여 BlueXP 디지털 지갑에서 BYOL을 활성화할 수 있습니다. BlueXP 재해 복구 비용은 데이터 저장소의 프로비저닝된 용량을 기반으로 합니다.

BlueXP 재해 복구의 라이센스 설정에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["라이센스를 설정합니다"].

모든 * BlueXP 서비스의 라이센스 관리에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["모든 BlueXP 서비스의 라이센스 관리"^].



=== 일정을 편집합니다

이 릴리즈에서는 이제 규정 준수 및 장애 조치 테스트를 테스트하는 일정을 설정하여 필요할 때 올바르게 작동하는지 확인할 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



== 2024년 2월 1일

이 BlueXP 재해 복구 사전 공개 릴리즈에는 다음 업데이트가 포함되어 있습니다.



=== 네트워크 개선

이 릴리즈에서는 이제 VM CPU 및 RAM 값의 크기를 조정할 수 있습니다. 이제 VM에 대한 네트워크 DHCP 또는 정적 IP 주소를 선택할 수도 있습니다.

* DHCP: 이 옵션을 선택하면 VM에 대한 자격 증명을 제공합니다.
* 정적 IP: 소스 VM에서 동일하거나 다른 정보를 선택할 수 있습니다. 원본과 동일한 을 선택하면 자격 증명을 입력할 필요가 없습니다. 반면 원본과 다른 정보를 사용하도록 선택한 경우 자격 증명, IP 주소, 서브넷 마스크, DNS 및 게이트웨이 정보를 제공할 수 있습니다.


자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== 사용자 정의 스크립트

이제 사후 페일오버 프로세스로 포함될 수 있습니다. 사용자 지정 스크립트를 사용하면 페일오버 프로세스 후에 BlueXP 재해 복구로 스크립트를 실행할 수 있습니다. 예를 들어, 페일오버가 완료된 후 사용자 지정 스크립트를 사용하여 모든 데이터베이스 트랜잭션을 재개할 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["원격 사이트로 페일오버"].



=== SnapMirror 관계

이제 복제 계획을 개발하는 동안 SnapMirror 관계를 생성할 수 있습니다. 이전에는 BlueXP 재해 복구 외부에 관계를 생성해야 했습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== 정합성 보장 그룹

복제 계획을 생성할 때 서로 다른 볼륨 및 SVM의 VM을 포함할 수 있습니다. BlueXP 재해 복구를 통해 모든 볼륨을 포함하여 일관성 그룹 스냅샷을 생성하고 모든 2차 위치를 업데이트합니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== VM 전원 켜기 지연 옵션

복제 계획을 생성할 때 리소스 그룹에 VM을 추가할 수 있습니다. 리소스 그룹을 사용하면 각 VM에 지연 시간을 설정하여 지연된 시퀀스에서 전원을 켤 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



=== 애플리케이션 정합성이 보장된 Snapshot 복사본

애플리케이션 정합성을 보장하는 스냅샷 복사본을 생성하도록 지정할 수 있습니다. 이 서비스는 응용 프로그램을 중지한 다음 스냅샷을 생성하여 응용 프로그램의 일관된 상태를 확보합니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].



== 2024년 1월 11일

이 BlueXP 재해 복구 사전 공개 릴리즈에는 다음 업데이트가 포함되어 있습니다.



=== 더 빠르게 대시보드

이 릴리즈를 사용하면 대시보드에서 다른 페이지의 정보에 더 빠르게 액세스할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].



== 2023년 10월 20일

이 BlueXP 재해 복구 기능의 사전 공개 릴리즈에는 다음 업데이트가 포함됩니다.



=== 온프레미스 NFS 기반 VMware 워크로드를 보호합니다

이제 BlueXP 재해 복구를 사용하면 퍼블릭 클라우드와 더불어 다른 온프레미스 NFS 기반 VMware 환경 재해로부터 온프레미스 NFS 기반 VMware 워크로드를 보호할 수 있습니다. BlueXP 재해 복구를 통해 재해 복구 계획의 완료를 조율합니다.


NOTE: 이 미리 보기 서비스를 통해 NetApp은 일반 출시 이전에 서비스 세부 정보, 콘텐츠 및 일정을 수정할 권한을 보유합니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].



== 2023년 9월 27일

이 BlueXP 재해 복구 사전 공개 릴리즈에는 다음 업데이트가 포함되어 있습니다.



=== 대시보드 업데이트

이제 대시보드의 옵션을 클릭하여 정보를 빠르게 검토할 수 있습니다. 또한 이제 대시보드에 페일오버 및 마이그레이션 상태가 표시됩니다.

을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["대시보드에서 재해 복구 계획의 상태를 확인합니다"].



=== 복제 계획 업데이트

* * RPO *: 이제 Replication Plan의 Datastores 섹션에 RPO(복구 지점 목표) 및 보존 카운트를 입력할 수 있습니다. 설정된 시간보다 오래되지 않은 존재해야 하는 데이터의 양을 나타냅니다. 예를 들어, 5분으로 설정할 경우 비즈니스 크리티컬 요구사항에 영향을 주지 않는 재해 발생 시 시스템에서 최대 5분의 데이터가 손실될 수 있습니다.
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].

* * 네트워킹 개선 사항 *: 복제 계획의 가상 머신 섹션에서 소스 및 대상 위치 간의 네트워킹을 매핑할 때 BlueXP 재해 복구는 이제 DHCP 또는 고정 IP의 두 가지 옵션을 제공합니다. 이전에는 DHCP만 지원되었습니다. 정적 IP의 경우 서브넷, 게이트웨이 및 DNS 서버를 구성합니다. 또한 이제 가상 머신에 대한 자격 증명을 입력할 수 있습니다.
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].

* * 스케줄 편집 * : 이제 복제 계획 스케줄을 업데이트할 수 있습니다.
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["자원 관리"].

* * SnapMirror 자동화 *: 이 릴리즈에서 복제 계획을 생성하는 동안 다음 구성 중 하나에서 소스 볼륨과 타겟 볼륨 간의 SnapMirror 관계를 정의할 수 있습니다.
+
** 1 대 1
** 팬아웃 아키텍처에 1개 또는 다대다
** 정합성 보장 그룹으로서 다대수 1입니다
** 다대다
+
을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"].







== 2023년 8월 1일



=== BlueXP  재해 복구 미리 보기

BlueXP 재해 복구 사전 공개는 재해 복구 워크플로우를 자동화하는 클라우드 기반 재해 복구 서비스입니다. 처음에는 BlueXP 재해 복구 미리보기를 통해 Amazon FSx for ONTAP를 통해 NetApp 스토리지를 실행하는 온프레미스 NFS 기반 VMware 워크로드를 AWS의 VMware Cloud(VMC)로 보호할 수 있습니다.


NOTE: 이 미리 보기 서비스를 통해 NetApp은 일반 출시 이전에 서비스 세부 정보, 콘텐츠 및 일정을 수정할 권한을 보유합니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].

이 릴리스에는 다음 업데이트가 포함됩니다.



=== 부트 순서를 위한 리소스 그룹 업데이트

재해 복구 또는 복제 계획을 생성할 때 가상 시스템을 기능 리소스 그룹에 추가할 수 있습니다. 리소스 그룹을 사용하면 요구 사항을 충족하는 논리적 그룹에 종속 가상 머신 세트를 배치할 수 있습니다. 예를 들어, 복구 시 실행할 수 있는 부팅 순서가 그룹에 포함될 수 있습니다. 이 릴리즈에서는 각 리소스 그룹에 하나 이상의 가상 머신을 포함할 수 있습니다. 가상 머신은 계획에 가상 머신을 포함하는 순서에 따라 전원이 켜집니다. 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["리소스 그룹을 복제하고 할당할 애플리케이션을 선택합니다"]참조하십시오.



=== 복제 검증

재해 복구 또는 복제 계획을 생성한 후 마법사에서 재발을 식별하고 재해 복구 사이트에 대한 복제를 시작하면 30분마다 BlueXP  재해 복구에서 계획에 따라 복제가 실제로 수행되는지 확인합니다. 작업 모니터 페이지에서 진행 상황을 모니터링할 수 있습니다. 을  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["애플리케이션을 다른 사이트에 복제"]참조하십시오.



=== 복제 계획에는 RPO(복구 지점 목표) 전송 일정이 표시됩니다

재해 복구 또는 복제 계획을 생성할 때 VM을 선택합니다. 이 릴리즈에서는 이제 데이터 저장소 또는 VM과 연결된 각 볼륨과 연결된 SnapMirror를 볼 수 있습니다. SnapMirror 일정과 연결된 RPO 전송 일정을 확인할 수도 있습니다. RPO는 백업 일정이 재해 발생 후 복구하기에 충분한지 여부를 확인하는 데 도움이 됩니다. 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



=== 작업 모니터 업데이트

작업 모니터 페이지에는 작업의 최신 상태를 확인할 수 있는 새로 고침 옵션이 포함되어 있습니다. 을  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["재해 복구 작업을 모니터링합니다"]참조하십시오.



== 2023년 5월 18일

BlueXP 재해 복구의 최초 릴리즈입니다.



=== 클라우드 기반 재해 복구 서비스

BlueXP 재해 복구는 재해 복구 워크플로우를 자동화하는 클라우드 기반 재해 복구 서비스입니다. 처음에는 BlueXP 재해 복구 미리보기를 통해 Amazon FSx for ONTAP를 통해 NetApp 스토리지를 실행하는 온프레미스 NFS 기반 VMware 워크로드를 AWS의 VMware Cloud(VMC)로 보호할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXP 재해 복구에 대해 자세히 알아보십시오"].
